### ISSUE TITLE
Ability to sort modpack list

### ISSUE THREAD

**Issue by TheWhoAreYouPerson** [Slowpoke101/FTBLaunch#947]
I think it would be a great feature launcher-side to be able to sort modpacks based on what the user wants. For example, by popularity (I think thats default atm?), by last update time, by which mcversion, alphabetical, etc. I don't think it would be that hard, but I'm not sure what system you are using to show the pack items, so I wont discuss that further. This system should also be usable in the map/texture pack interfaces as well, if I had to image. (Most compatible texture pack?)

**Comment by jikuja** [comment]
Let's analyze this:
1. "by popularity"/"by last update time" no data in pack XMLs. Adding that information would require server side changes or changes in pack update procuderes Current sorting is done manually in xml files. Private pack codes are sorted by that order user has added them.
2. "mcversion" would require sortable mcversion. That is easy-ish to add if needed but...
3. "alphabetical" easy to implement by adding new Comparator. I tested this earlier but decided not to commit my code because...

Adding sorting features requires more buttons => GUI rewrites. Current Curse transition is main reason not to do major (GUI) rewrites.

**Comment by TheWhoAreYouPerson** [comment]
All those points are fair enough, I understand that the new Curse launcher is a major reason not to do any major rewrites to the default launcher. Just looking for more fancy features, since us linux users don't get a native curse client yet. Honestly id rather have something akin to a FTB or Curse plugin for MultiMC, but I dont see anything about making plugins. Thanks for thinking about it though, means alot!
